theme: jekyll-theme-minimal
title: Advanced Scientific Visualization Assignment 3
description: My webpage
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Setup
    url: setup
  - title: niz uptake
    url: niz
